port : $(arg driver_port)
baud : 115200

# specify robot track width in meters
track_width: 1.0025 # +1 cm compared to aristos' 0.9925
# specify reduction ratio (70:1), if there is no put 1
reduction_ratio: 70
# specify reduction maximum linear velocity (m/s)
# max_vel: 0.95  # 60 m/min @3500rpm
max_vel: 0.42  # reduced speed for testing
# specify robot wheel circumference (perimeter) in meters 
wheel_circumference: 1.162389 # D:37cm
encoder_cpr: 1000 # 1000 pulses per revolution * 4, because of the quadratic mode  
encoder_min: -2147483648.0
encoder_max:  2147483648.0 
rate: 20 
enable_imu_yaw: $(arg use_imu)
imu_topic: $(arg imu_topic)
wrp_lim: 0.3
sub_to_abs: false
imu_discarded: 100
tf_publish: false
odom_topic: odom
tf_header_frame: $(arg prefix)odom
tf_child_frame: $(arg prefix)base_footprint
odom_frame: $(arg prefix)odom



frequencyH : 50   #higher frequency (value is in ms)

queryH:
 motor_amps : ?A 
 motor_command : ?M
# hall_count : ?BCR
# abs_hall_count : ?CB
# hall_speed : ?BS
 volts : ?V
 feedback : ?F 
 battery_amps : ?BA
 power : ?P          
 fault_flag : ?FF  
 sto_status : ?STT 
#  status_flag : ?FS
# motor_amps2 : ?MA
# motor_command2 : ?FM
# hall_count2 : ?FM
# hall_speed2 : ?FS
# volts2 : ?V
# feedback2 : ?rmp 
# battery_amps2 : ?PHA
# power2 : ?sns          
# fault_flag2 : ?S  
# status_flag : ?FS
# firmware_id : ?FID  
 encoder_count : ?C
 encoder_count_relative : ?CR
 encoder_speed : ?S  

