/**:
  ros__parameters:
    serial:
      port: /dev/ttyACM0
      baud: 115200

    encoder:
      cpr: 10000 # with quadrature
    
    queries_list: ["CR", "S"]

    queries:
      CR:
        name: "encoder_count_relative"
        size: 2
      S:
        name: "encoder_motor_speed"
        size: 2