/**:
  ros__parameters:
    serial:
      port: /dev/ttyROBOTEQ
      baud: 115200
    
    queries_list: ["CR", "S", "F"]

    queries:
      CR:
        name: "encoder_count_relative"
        size: 2
      S:
        name: "encoder_motor_speed"
        size: 2
      F:
        name: "feedback"
        size: 2    