/**:
  ros__parameters:
    serial:
      port: /dev/ttyROBOTEQ
      baud: 115200

    encoder:
      cpr: 10000 # with quadrature
    
    queries_list: ["CR", "S", "FS", "FF", "FM"]

    queries:
      CR:
        name: "encoder_count_relative"
        size: 2
      S:
        name: "encoder_motor_speed"
        size: 2
      FF:
        name: "fault_flag"
        size: 1
      FS:
        name: "status_flag"
        size: 1
      FM:
        name: "runtime_status_flag"
        size: 1